#include "ntstatus.h"

const char *ntstatus_to_string(NTSTATUS r)
{
	switch (r)
	{
#define S(x) case x: return #x;
	S(STATUS_UNSUCCESSFUL)
	S(STATUS_NOT_IMPLEMENTED)
	S(STATUS_INVALID_INFO_CLASS)
	S(STATUS_INFO_LENGTH_MISMATCH)
	S(STATUS_ACCESS_VIOLATION)
	S(STATUS_INVALID_HANDLE)
	S(STATUS_INVALID_CID)
	S(STATUS_INVALID_PARAMETER)
	S(STATUS_NO_SUCH_FILE)
	S(STATUS_NO_MEMORY)
	S(STATUS_CONFLICTING_ADDRESSES)
	S(STATUS_UNABLE_TO_FREE_VM)
	S(STATUS_INVALID_SYSTEM_SERVICE)
	S(STATUS_ILLEGAL_INSTRUCTION)
	S(STATUS_INVALID_FILE_FOR_SECTION)
	S(STATUS_ACCESS_DENIED)
	S(STATUS_BUFFER_TOO_SMALL)
	S(STATUS_OBJECT_TYPE_MISMATCH)
	S(STATUS_NOT_COMMITTED)
	S(STATUS_INVALID_PARAMETER_2)
	S(STATUS_INVALID_PARAMETER_3)
	S(STATUS_INVALID_PARAMETER_4)
	S(STATUS_INVALID_PARAMETER_5)
	S(STATUS_INVALID_PARAMETER_6)
	S(STATUS_INVALID_ADDRESS)
#undef S
	default:
		return "unknown";
	}
}
